export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

export const FETCH_CURRENT_USER_SUCCESS = "FETCH_CURRENT_USER_SUCCESS";
export const FETCH_CURRENT_USER_FAIL = "FETCH_CURRENT_USER_FAIL";
export const FETCH_CURRENT_USER_START = "FETCH_CURRENT_USER_START";

export const FETCH_SINGLE_ARTICLE_SUCCESS = "FETCH_SINGLE_ARTICLE_SUCCESS";
export const FETCH_SINGLE_ARTICLE_FAIL = "FETCH_SINGLE_ARTICLE_FAIL";
export const FETCH_SINGLE_ARTICLE_START = "FETCH_SINGLE_ARTICLE_START";

export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS";
export const POST_COMMENT_FAIL = "POST_COMMENT_FAIL";
export const POST_COMMENT_START = "POST_COMMENT_START";

export const FETCH_COMMENTS_SUCCESS = "FETCH_COMMENTS_SUCCESS";
export const FETCH_COMMENTS_FAIL = "FETCH_COMMENTS_FAIL";
export const FETCH_COMMENTS_START = "FETCH_COMMENTS_START";

export const FETCH_PROFILE_USER_SUCCESS = "FETCH_PROFILE_USER_SUCCESS";
export const FETCH_PROFILE_USER_FAIL = "FETCH_PROFILE_USER_FAIL";
export const FETCH_PROFILE_USER_START = "FETCH_PROFILE_USER_START";

export const EDIT_PROFILE_USER_SUCCESS = "EDIT_PROFILE_USER_SUCCESS";
export const EDIT_PROFILE_USER_FAIL = "EDIT_PROFILE_USER_FAIL";
export const EDIT_PROFILE_USER_START = "EDIT_PROFILE_USER_START";

export const EDIT_USER_PIC_SUCCESS = "EDIT_USER_PIC_SUCCESS";
export const EDIT_USER_PIC_FAIL = "EDIT_USER_PIC_FAIL";
export const EDIT_USER_PIC_START = "EDIT_USER_PIC_START";

export const GET_USER_PIC_SUCCESS = "GET_USER_PIC_SUCCESS";
export const GET_USER_PIC_FAIL = "GET_USER_PIC_FAIL";
export const GET_USER_PIC_START = "GET_USER_PIC_START";

export const CREATE_PROFILE_USER_SUCCESS = "CREATE_PROFILE_USER_SUCCESS";
export const CREATE_PROFILE_USER_FAIL = "CREATE_PROFILE_USER_FAIL";
export const CREATE_PROFILE_USER_START = "CREATE_PROFILE_USER_START";

export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS";
export const FETCH_CATEGORY_FAIL = "FETCH_CATEGORY_FAIL";
export const FETCH_CATEGORY_START = "FETCH_CATEGORY_START";

export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_FAIL = "FETCH_CATEGORIES_FAIL";
export const FETCH_CATEGORIES_START = "FETCH_CATEGORIES_START";

export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_FAIL = "CREATE_CATEGORY_FAIL";
export const CREATE_CATEGORY_START = "CREATE_CATEGORY_START";

export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAIL = "DELETE_CATEGORY_FAIL";
export const DELETE_CATEGORY_START = "DELETE_CATEGORY_START";

export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_FAIL = "UPDATE_CATEGORY_FAIL";
export const UPDATE_CATEGORY_START = "UPDATE_CATEGORY_START";

export const GET_ONE_CATEGORY_SUCCESS = "GET_ONE_CATEGORY_SUCCESS";
export const GET_ONE_CATEGORY_FAIL = "GET_ONE_CATEGORY_FAIL";
export const GET_ONE_CATEGORY_START = "GET_ONE_CATEGORY_START";
export const POST_ARTICLE_SUCCESS = "POST_ARTICLE_SUCCESS";
export const POST_ARTICLE_FAIL = "POST_ARTICLE_FAIL";
export const POST_ARTICLE_START = "POST_ARTICLE_START";

export const FOLLOW_USER_SUCCESS = "FOLLOW_USER_SUCCESS";
export const UNFOLLOW_USER_SUCCESS = "UNFOLLOW_USER_SUCCESS";
export const UNFOLLOW_USER_FAIL = "UNFOLLOW_USER_FAIL";
export const FOLLOW_USER_FAIL = "FOLLOW_USER_FAIL";
export const FOLLOW_USER_START = "FOLLOW_USER_START";

export const FETCH_FOLLOWERS_SUCCESS = "FETCH_FOLLOWERS_SUCCESS";
export const FETCH_FOLLOWERS_FAIL = "FETCH_FOLLOWERS_FAIL";
export const FETCH_FOLLOWERS_START = "FETCH_FOLLOWERS_START";

export const FETCH_FOLLOWING_SUCCESS = "FETCH_FOLLOWING_SUCCESS";
export const FETCH_FOLLOWING_FAIL = "FETCH_FOLLOWING_FAIL";
export const FETCH_FOLLOWING_START = "FETCH_FOLLOWING_START";
export const CLEAR_FOLLOW = "CLEAR_FOLLOW";

export const LIKE_ARTICLE_SUCCESS = "LIKE_ARTICLE_SUCCESS";
export const LIKE_ARTICLE_FAIL = "LIKE_ARTICLE_FAIL";
export const LIKE_ARTICLE_START = "LIKE_ARTICLE_START";

export const UPLOAD_IMG_SUCCESS = "UPLOAD_IMG_SUCCESS";
export const UPLOAD_IMG_FAIL = "UPLOAD_IMG_FAIL";
export const UPLOAD_IMG_START = "UPLOAD_IMG_START";

export const CLEAR_POST_ARTICLE = "CLEAR_POST_ARTICLE";
