export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const FETCH_CURRENT_USER_SUCCESS = 'FETCH_CURRENT_USER_SUCCESS';
export const FETCH_CURRENT_USER_FAIL = 'FETCH_CURRENT_USER_FAIL';
export const FETCH_CURRENT_USER_START = 'FETCH_CURRENT_USER_START';

export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS';
export const FETCH_CATEGORY_FAIL = 'FETCH_CATEGORY_FAIL';
export const FETCH_CATEGORY_START = 'FETCH_CATEGORY_START';

export const FETCH_SINGLE_ARTICLE_SUCCESS = 'FETCH_SINGLE_ARTICLE_SUCCESS';
export const FETCH_SINGLE_ARTICLE_FAIL = 'FETCH_SINGLE_ARTICLE_FAIL';
export const FETCH_SINGLE_ARTICLE_START = 'FETCH_SINGLE_ARTICLE_START';

export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS';
export const POST_COMMENT_FAIL = 'POST_COMMENT_FAIL';
export const POST_COMMENT_START = 'POST_COMMENT_START';

export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_FAIL = 'FETCH_COMMENTS_FAIL';
export const FETCH_COMMENTS_START = 'FETCH_COMMENTS_START';
